name: sparks
description: "Interns Manager"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.4.2

  flutter_inner_shadow: 0.0.1

  fl_chart: ^0.70.2

  pie_chart: ^5.4.0

  cupertino_icons: ^1.0.8

  flutter_svg: ^2.0.17

  lottie: ^3.1.0

  audioplayers: ^6.4.0

  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  url_launcher: ^6.3.1
  mailer: ^6.4.1
  flutter_local_notifications: ^19.2.1
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_local_notifications: ^19.2.1

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/sounds/splash_sound.mp3
    - assets/fonts/NotoSans-Regular.ttf

